version: '3'

services:

  api:
    build: ./api
    container_name: train-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=http://train-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    container_name: train-docker-api-db
    volumes:
      - mongodb_api:/data/db

  auth:
    build: ./auth
    command: npm run dev
    container_name: train-docker-auth
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://train-docker.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  auth_db:
    image: mongo:latest
    container_name: train-docker-auth-db
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth:
